syntax = "proto3";
package klyraprotocol.subaccounts;

option go_package = "github.com/StreamFinance-Protocol/stream-chain/protocol/x/subaccounts/types";

import "cosmos/msg/v1/msg.proto";
import "klyraprotocol/subaccounts/subaccount.proto";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;
  // ClaimYieldsForSubaccount claims the yields for the provided subaccount and
  // persists it to state.
  rpc ClaimYieldsForSubaccount(MsgClaimYieldsForSubaccount)
      returns (MsgClaimYieldsForSubaccountResponse);
}

// MsgClaimYieldsForSubaccount is the Msg/ClaimYieldsForSubaccount request type.
message MsgClaimYieldsForSubaccount { SubaccountId id = 1; }

// MsgClaimYieldsForSubaccountResponse is the Msg/ClaimYieldsForSubaccount
// response type.
message MsgClaimYieldsForSubaccountResponse {}