// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: klyraprotocol/ratelimit/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GetSDAIPriceRequest is a request type for the GetSDAIPrice RPC method.
type GetSDAIPriceQueryRequest struct {
}

func (m *GetSDAIPriceQueryRequest) Reset()         { *m = GetSDAIPriceQueryRequest{} }
func (m *GetSDAIPriceQueryRequest) String() string { return proto.CompactTextString(m) }
func (*GetSDAIPriceQueryRequest) ProtoMessage()    {}
func (*GetSDAIPriceQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc33bde80a52312, []int{0}
}
func (m *GetSDAIPriceQueryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSDAIPriceQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSDAIPriceQueryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetSDAIPriceQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSDAIPriceQueryRequest.Merge(m, src)
}
func (m *GetSDAIPriceQueryRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetSDAIPriceQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSDAIPriceQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSDAIPriceQueryRequest proto.InternalMessageInfo

// GetSDAIPriceResponse is a response type for the GetSDAIPrice RPC method.
type GetSDAIPriceQueryResponse struct {
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (m *GetSDAIPriceQueryResponse) Reset()         { *m = GetSDAIPriceQueryResponse{} }
func (m *GetSDAIPriceQueryResponse) String() string { return proto.CompactTextString(m) }
func (*GetSDAIPriceQueryResponse) ProtoMessage()    {}
func (*GetSDAIPriceQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc33bde80a52312, []int{1}
}
func (m *GetSDAIPriceQueryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSDAIPriceQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSDAIPriceQueryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetSDAIPriceQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSDAIPriceQueryResponse.Merge(m, src)
}
func (m *GetSDAIPriceQueryResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetSDAIPriceQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSDAIPriceQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSDAIPriceQueryResponse proto.InternalMessageInfo

func (m *GetSDAIPriceQueryResponse) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

// GetAssetYieldIndexRequest is a request type for the GetAssetYieldIndex RPC
// method.
type GetAssetYieldIndexQueryRequest struct {
}

func (m *GetAssetYieldIndexQueryRequest) Reset()         { *m = GetAssetYieldIndexQueryRequest{} }
func (m *GetAssetYieldIndexQueryRequest) String() string { return proto.CompactTextString(m) }
func (*GetAssetYieldIndexQueryRequest) ProtoMessage()    {}
func (*GetAssetYieldIndexQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc33bde80a52312, []int{2}
}
func (m *GetAssetYieldIndexQueryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAssetYieldIndexQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAssetYieldIndexQueryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAssetYieldIndexQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetYieldIndexQueryRequest.Merge(m, src)
}
func (m *GetAssetYieldIndexQueryRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetAssetYieldIndexQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetYieldIndexQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetYieldIndexQueryRequest proto.InternalMessageInfo

// GetSDAIPriceQueryResponse is a response type for the GetAssetYieldIndex RPC
// method.
type GetAssetYieldIndexQueryResponse struct {
	AssetYieldIndex string `protobuf:"bytes,1,opt,name=asset_yield_index,json=assetYieldIndex,proto3" json:"asset_yield_index,omitempty"`
}

func (m *GetAssetYieldIndexQueryResponse) Reset()         { *m = GetAssetYieldIndexQueryResponse{} }
func (m *GetAssetYieldIndexQueryResponse) String() string { return proto.CompactTextString(m) }
func (*GetAssetYieldIndexQueryResponse) ProtoMessage()    {}
func (*GetAssetYieldIndexQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecc33bde80a52312, []int{3}
}
func (m *GetAssetYieldIndexQueryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAssetYieldIndexQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAssetYieldIndexQueryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAssetYieldIndexQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetYieldIndexQueryResponse.Merge(m, src)
}
func (m *GetAssetYieldIndexQueryResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAssetYieldIndexQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetYieldIndexQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetYieldIndexQueryResponse proto.InternalMessageInfo

func (m *GetAssetYieldIndexQueryResponse) GetAssetYieldIndex() string {
	if m != nil {
		return m.AssetYieldIndex
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSDAIPriceQueryRequest)(nil), "klyraprotocol.ratelimit.GetSDAIPriceQueryRequest")
	proto.RegisterType((*GetSDAIPriceQueryResponse)(nil), "klyraprotocol.ratelimit.GetSDAIPriceQueryResponse")
	proto.RegisterType((*GetAssetYieldIndexQueryRequest)(nil), "klyraprotocol.ratelimit.GetAssetYieldIndexQueryRequest")
	proto.RegisterType((*GetAssetYieldIndexQueryResponse)(nil), "klyraprotocol.ratelimit.GetAssetYieldIndexQueryResponse")
}

func init() {
	proto.RegisterFile("klyraprotocol/ratelimit/query.proto", fileDescriptor_ecc33bde80a52312)
}

var fileDescriptor_ecc33bde80a52312 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x41, 0x6b, 0xe2, 0x40,
	0x14, 0x36, 0xbb, 0xb8, 0xb0, 0x73, 0x59, 0x1c, 0x04, 0xdd, 0xb0, 0x64, 0x25, 0x7b, 0x59, 0x64,
	0xcd, 0xa0, 0x2e, 0xec, 0xf6, 0x68, 0x29, 0x15, 0x0f, 0x05, 0xab, 0xa7, 0xf6, 0x12, 0xc6, 0xf8,
	0x88, 0x43, 0xe3, 0x4c, 0xcc, 0x8c, 0xc5, 0x5c, 0xfd, 0x05, 0x85, 0xfe, 0x8f, 0xfe, 0x8d, 0xf6,
	0x28, 0xf4, 0xd2, 0x63, 0xd1, 0xfe, 0x90, 0x92, 0xc4, 0x8a, 0xc1, 0xc6, 0xe2, 0x6d, 0xe6, 0x7d,
	0xdf, 0x7b, 0xdf, 0xfb, 0xbe, 0x87, 0x7e, 0x5d, 0x79, 0x61, 0x40, 0xfd, 0x40, 0x28, 0xe1, 0x08,
	0x8f, 0x04, 0x54, 0x81, 0xc7, 0xc6, 0x4c, 0x91, 0xc9, 0x14, 0x82, 0xd0, 0x8a, 0x01, 0x5c, 0x4a,
	0x91, 0xac, 0x0d, 0x49, 0x2f, 0xba, 0xc2, 0x15, 0x71, 0x9d, 0x44, 0xaf, 0x84, 0xae, 0xff, 0x70,
	0x85, 0x70, 0x3d, 0x20, 0xd4, 0x67, 0x84, 0x72, 0x2e, 0x14, 0x55, 0x4c, 0x70, 0x99, 0xa0, 0xa6,
	0x8e, 0xca, 0x6d, 0x50, 0xfd, 0x93, 0x56, 0xa7, 0x1b, 0x30, 0x07, 0xce, 0x23, 0x9d, 0x1e, 0x4c,
	0xa6, 0x20, 0x95, 0x59, 0x47, 0xdf, 0xdf, 0xc1, 0xa4, 0x2f, 0xb8, 0x04, 0x5c, 0x44, 0x79, 0x3f,
	0xaa, 0x96, 0xb5, 0x8a, 0xf6, 0xfb, 0x6b, 0x2f, 0xf9, 0x98, 0x15, 0x64, 0xb4, 0x41, 0xb5, 0xa4,
	0x04, 0x75, 0xc1, 0xc0, 0x1b, 0x76, 0xf8, 0x10, 0x66, 0xa9, 0xa1, 0x67, 0xe8, 0x67, 0x26, 0x63,
	0x3d, 0xba, 0x8a, 0x0a, 0x34, 0xc2, 0xed, 0x30, 0x22, 0xd8, 0x2c, 0x62, 0xac, 0x65, 0xbe, 0xd1,
	0x74, 0x63, 0x63, 0xfe, 0x19, 0xe5, 0xe3, 0x6e, 0x7c, 0xa7, 0xa1, 0xc2, 0xce, 0xba, 0xb8, 0x6e,
	0x65, 0xa4, 0x65, 0x65, 0xd9, 0xd6, 0x1b, 0x87, 0xb4, 0x24, 0x2b, 0x9b, 0x8d, 0xf9, 0xe3, 0xcb,
	0xed, 0xa7, 0x3f, 0xb8, 0x4a, 0xd2, 0x17, 0xbc, 0xfe, 0xbb, 0x75, 0x44, 0x17, 0x94, 0x2d, 0x87,
	0x94, 0xd9, 0x71, 0x56, 0xf8, 0x5e, 0x43, 0xa5, 0x8c, 0x28, 0xf0, 0xbf, 0x7d, 0x3b, 0xec, 0x89,
	0x57, 0xff, 0x7f, 0x78, 0xe3, 0xda, 0xc2, 0x51, 0x6c, 0xa1, 0x89, 0xeb, 0x1f, 0x59, 0xd8, 0xb9,
	0xcd, 0xb1, 0xf3, 0xb0, 0x34, 0xb4, 0xc5, 0xd2, 0xd0, 0x9e, 0x97, 0x86, 0x76, 0xb3, 0x32, 0x72,
	0x8b, 0x95, 0x91, 0x7b, 0x5a, 0x19, 0xb9, 0xcb, 0x8e, 0xcb, 0xd4, 0x68, 0x3a, 0xb0, 0x1c, 0x31,
	0x26, 0x7d, 0x15, 0x00, 0x1d, 0x9f, 0x32, 0x4e, 0xb9, 0x03, 0xb5, 0xee, 0xdb, 0x7c, 0x19, 0x97,
	0x6b, 0xce, 0x88, 0x32, 0x4e, 0x36, 0xaa, 0xb3, 0x2d, 0x51, 0x15, 0xfa, 0x20, 0x07, 0x5f, 0x62,
	0xac, 0xf9, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xe5, 0xf9, 0x05, 0x24, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Get the price of sDAI.
	GetSDAIPriceQuery(ctx context.Context, in *GetSDAIPriceQueryRequest, opts ...grpc.CallOption) (*GetSDAIPriceQueryResponse, error)
	// Get the price of sDAI.
	GetAssetYieldIndexQuery(ctx context.Context, in *GetAssetYieldIndexQueryRequest, opts ...grpc.CallOption) (*GetAssetYieldIndexQueryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetSDAIPriceQuery(ctx context.Context, in *GetSDAIPriceQueryRequest, opts ...grpc.CallOption) (*GetSDAIPriceQueryResponse, error) {
	out := new(GetSDAIPriceQueryResponse)
	err := c.cc.Invoke(ctx, "/klyraprotocol.ratelimit.Query/GetSDAIPriceQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAssetYieldIndexQuery(ctx context.Context, in *GetAssetYieldIndexQueryRequest, opts ...grpc.CallOption) (*GetAssetYieldIndexQueryResponse, error) {
	out := new(GetAssetYieldIndexQueryResponse)
	err := c.cc.Invoke(ctx, "/klyraprotocol.ratelimit.Query/GetAssetYieldIndexQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Get the price of sDAI.
	GetSDAIPriceQuery(context.Context, *GetSDAIPriceQueryRequest) (*GetSDAIPriceQueryResponse, error)
	// Get the price of sDAI.
	GetAssetYieldIndexQuery(context.Context, *GetAssetYieldIndexQueryRequest) (*GetAssetYieldIndexQueryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetSDAIPriceQuery(ctx context.Context, req *GetSDAIPriceQueryRequest) (*GetSDAIPriceQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSDAIPriceQuery not implemented")
}
func (*UnimplementedQueryServer) GetAssetYieldIndexQuery(ctx context.Context, req *GetAssetYieldIndexQueryRequest) (*GetAssetYieldIndexQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetYieldIndexQuery not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetSDAIPriceQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSDAIPriceQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSDAIPriceQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/klyraprotocol.ratelimit.Query/GetSDAIPriceQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSDAIPriceQuery(ctx, req.(*GetSDAIPriceQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAssetYieldIndexQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetYieldIndexQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAssetYieldIndexQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/klyraprotocol.ratelimit.Query/GetAssetYieldIndexQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAssetYieldIndexQuery(ctx, req.(*GetAssetYieldIndexQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "klyraprotocol.ratelimit.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSDAIPriceQuery",
			Handler:    _Query_GetSDAIPriceQuery_Handler,
		},
		{
			MethodName: "GetAssetYieldIndexQuery",
			Handler:    _Query_GetAssetYieldIndexQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "klyraprotocol/ratelimit/query.proto",
}

func (m *GetSDAIPriceQueryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSDAIPriceQueryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSDAIPriceQueryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetSDAIPriceQueryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSDAIPriceQueryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSDAIPriceQueryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAssetYieldIndexQueryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAssetYieldIndexQueryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAssetYieldIndexQueryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetAssetYieldIndexQueryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAssetYieldIndexQueryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAssetYieldIndexQueryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetYieldIndex) > 0 {
		i -= len(m.AssetYieldIndex)
		copy(dAtA[i:], m.AssetYieldIndex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AssetYieldIndex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetSDAIPriceQueryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetSDAIPriceQueryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetAssetYieldIndexQueryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetAssetYieldIndexQueryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetYieldIndex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetSDAIPriceQueryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSDAIPriceQueryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSDAIPriceQueryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSDAIPriceQueryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSDAIPriceQueryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSDAIPriceQueryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAssetYieldIndexQueryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAssetYieldIndexQueryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAssetYieldIndexQueryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAssetYieldIndexQueryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAssetYieldIndexQueryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAssetYieldIndexQueryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetYieldIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetYieldIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
