version: "3"

services:
  klyraprotocold0:
    image: local:klyraprotocol
    entrypoint:
      - cosmovisor
      - run
      - start
      - --log_level
      # Note that only this validator has a log-level of `info`; other validators use `error` by default.
      # Change to `debug` for more verbose log-level.
      - info
      - --home
      - /klyraprotocol/chain/.alice
      - --p2p.persistent_peers
      - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@klyraprotocold0:26656,b69182310be02559483e42c77b7b104352713166@klyraprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@klyraprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@klyraprotocold3:26656"
      - --dd-error-tracking-format
      - "true"
      - --max-daemon-unhealthy-seconds
      - "4294967295" # Effectively disable the daemon monitor because bridge daemon is flaky in localnet. Note: bridge daemon is deprecated.
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/klyraprotocol/chain/.alice
    volumes:
      - ./localnet/klyraprotocol0:/klyraprotocol/chain/.alice/data
    ports:
      - "26657:26657"
      - "9090:9090"
      - "1317:1317"

  klyraprotocold1:
    image: local:klyraprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /klyraprotocol/chain/.bob
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@klyraprotocold0:26656,b69182310be02559483e42c77b7b104352713166@klyraprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@klyraprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@klyraprotocold3:26656"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/klyraprotocol/chain/.bob
    volumes:
      - ./localnet/klyraprotocol1:/klyraprotocol/chain/.bob/data
    ports:
      - "26658:26657"

  klyraprotocold2:
    image: local:klyraprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /klyraprotocol/chain/.carl
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@klyraprotocold0:26656,b69182310be02559483e42c77b7b104352713166@klyraprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@klyraprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@klyraprotocold3:26656"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/klyraprotocol/chain/.carl
    volumes:
      - ./localnet/klyraprotocol2:/klyraprotocol/chain/.carl/data

  klyraprotocold3:
    image: local:klyraprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /klyraprotocol/chain/.dave
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@klyraprotocold0:26656,b69182310be02559483e42c77b7b104352713166@klyraprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@klyraprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@klyraprotocold3:26656"
       - --dd-error-tracking-format
       - "true"
       - --max-daemon-unhealthy-seconds
       - "4294967295"
    environment:
      # See https://docs.datadoghq.com/profiler/enabling/go/ for DD_ specific environment variables
      - DD_ENV=localnet_${USER}
      - DD_AGENT_HOST=datadog-agent
      - DAEMON_HOME=/klyraprotocol/chain/.dave
    volumes:
      - ./localnet/klyraprotocol3:/klyraprotocol/chain/.dave/data

  datadog-agent:
    image: public.ecr.aws/datadog/agent:7
    environment:
      # See https://docs.datadoghq.com/containers/docker/?tab=standard#environment-variables for agent configuration
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8125:8215"
      - "8126:8126"
