version: '3'

x-env: &env
  environment: # Docker Compose overrides
    DB_HOSTNAME: postgres
    DB_READONLY_HOSTNAME: postgres
    KAFKA_BROKER_URLS: kafka:9092
    REDIS_URL: redis://redis:6379

services:
  kafka:
    image: blacktop/kafka:2.6
    env_file:
      - .env.kafka
    environment: # Only for Docker Compose overrides
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - 9092:9092
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic to-websockets-candles --describe"]
      interval: 5s
      timeout: 20s
      retries: 50

  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6379:6379

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres.local
    env_file:
      - .env.postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U klyra_dev"]
      interval: 5s
      timeout: 20s
      retries: 10

  postgres-package:
    build:
      context: .
      dockerfile: Dockerfile.postgres-package.local
    depends_on:
      postgres:
        condition: service_healthy

  ender:
    <<: *env
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        service: ender
    env_file:
      - ./services/ender/.env
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      postgres-package:
        condition: service_completed_successfully

  comlink:
    <<: *env
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        service: comlink
    env_file:
      - ./services/comlink/.env
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      postgres-package:
        condition: service_completed_successfully

  socks:
    <<: *env
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        service: socks
    env_file:
      - ./services/socks/.env
    ports:
      - 3001:3001
      - 3002:3002
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      postgres-package:
        condition: service_completed_successfully

  roundtable:
    <<: *env
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        service: roundtable
    env_file:
      - ./services/roundtable/.env
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      postgres-package:
        condition: service_completed_successfully

  vulcan:
    <<: *env
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        service: vulcan
    env_file:
      - ./services/vulcan/.env
    depends_on:
      kafka:
        condition: service_healthy
