// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	big "math/big"

	types "github.com/cosmos/cosmos-sdk/types"
	mock "github.com/stretchr/testify/mock"
)

// VEApplierYieldKeeper is an autogenerated mock type for the VEApplierYieldKeeper type
type VEApplierYieldKeeper struct {
	mock.Mock
}

// ProcessNewSDaiConversionRateUpdate provides a mock function with given fields: ctx, sDaiConversionRate, blockHeight
func (_m *VEApplierYieldKeeper) ProcessNewSDaiConversionRateUpdate(ctx types.Context, sDaiConversionRate *big.Int, blockHeight *big.Int) error {
	ret := _m.Called(ctx, sDaiConversionRate, blockHeight)

	if len(ret) == 0 {
		panic("no return value specified for ProcessNewSDaiConversionRateUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Context, *big.Int, *big.Int) error); ok {
		r0 = rf(ctx, sDaiConversionRate, blockHeight)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVEApplierYieldKeeper creates a new instance of VEApplierYieldKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVEApplierYieldKeeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *VEApplierYieldKeeper {
	mock := &VEApplierYieldKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
