services:
  kafka:
    image: blacktop/kafka:2.6
    env_file:
      - ../indexer/.env.kafka
    environment: # Only for Docker Compose overrides
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - 9092:9092
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic to-websockets-candles --describe"]
      interval: 5s
      timeout: 20s
      retries: 50

  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6379:6379

  postgres:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.postgres.local
    env_file:
      - ../indexer/.env.postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U klyra_dev"]
      interval: 5s
      timeout: 20s
      retries: 10

  postgres-package:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.postgres-package.local
    depends_on:
      postgres:
        condition: service_healthy

  ender:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service
      args:
        service: ender
    env_file:
      - ../indexer/services/ender/.env
    environment: # Docker Compose overrides
      DB_HOSTNAME: postgres
      DB_READONLY_HOSTNAME: postgres
      KAFKA_BROKER_URLS: kafka:9092
      REDIS_URL: redis://redis:6379
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      postgres-package:
        condition: service_completed_successfully

  comlink:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service
      args:
        service: comlink
    env_file:
      - ../indexer/services/comlink/.env
    environment: # Docker Compose overrides
      DB_HOSTNAME: postgres
      DB_READONLY_HOSTNAME: postgres
      REDIS_URL: redis://redis:6379
      RATE_LIMIT_REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      postgres-package:
        condition: service_completed_successfully

  socks:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service
      args:
        service: socks
    env_file:
      - ../indexer/services/socks/.env
    environment: # Docker Compose overrides
      DB_HOSTNAME: postgres
      DB_READONLY_HOSTNAME: postgres
      KAFKA_BROKER_URLS: kafka:9092
    ports:
      - 3001:3001
      - 3002:3002
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      postgres-package:
        condition: service_completed_successfully

  roundtable:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service
      args:
        service: roundtable
    env_file:
      - ../indexer/services/roundtable/.env
    environment: # Docker Compose overrides
      DB_HOSTNAME: postgres
      DB_READONLY_HOSTNAME: postgres
      KAFKA_BROKER_URLS: kafka:9092
      REDIS_URL: redis://redis:6379
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      postgres-package:
        condition: service_completed_successfully

  vulcan:
    build:
      context: ../indexer
      dockerfile: ../indexer/Dockerfile.service
      args:
        service: vulcan
    env_file:
      - ../indexer/services/vulcan/.env
    environment: # Docker Compose overrides
      DB_HOSTNAME: postgres
      DB_READONLY_HOSTNAME: postgres
      KAFKA_BROKER_URLS: kafka:9092
      REDIS_URL: redis://redis:6379
    depends_on:
      kafka:
        condition: service_healthy

  klyraprotocold0:
    image: local:e2etest-klyraprotocol
    entrypoint:
      - cosmovisor
      - run
      - start
      - --log_level
      # Note that only this validator has a log-level of `info`; other validators use `error` by default.
      # Change to `debug` for more verbose log-level.
      - info 
      - --home
      - /klyraprotocol/chain/.alice
      - --p2p.persistent_peers 
      - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@klyraprotocold0:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@klyraprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@klyraprotocold3:26656"
      - --sDAI-daemon-mock-no-yields
      - "true"
      - --sDai-daemon-enabled
      - "true"
      - --price-daemon-enabled
      - "true"
      - --deleveraging-daemon-enabled
      - "true"
    environment:
      - DAEMON_HOME=/klyraprotocol/chain/.alice
      - ETH_RPC_ENDPOINT
    volumes:
      - ../protocol/localnet/klyraprotocol0:/klyraprotocol/chain/.alice/data
    ports:
      - "26657:26657"
      - "9090:9090"
      - "1317:1317"

  # This is the Indexer connected node.
  # TODO: remove stake and make this a full node.
  klyraprotocold1:
    image: local:e2etest-klyraprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /klyraprotocol/chain/.bob
       - --p2p.persistent_peers 
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@klyraprotocold0:26656,b69182310be02559483e42c77b7b104352713166@klyraprotocold1:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@klyraprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@klyraprotocold3:26656"
       - --non-validating-full-node=true
       - --indexer-kafka-conn-str
       - "kafka:9092"
       - --sDAI-daemon-mock-no-yields
       - "true"
    environment:
      - DAEMON_HOME=/klyraprotocol/chain/.bob
    volumes:
      - ../protocol/localnet/klyraprotocol1:/klyraprotocol/chain/.bob/data
    ports:
      - "26658:26657"
    depends_on:
      kafka:
        condition: service_healthy

  klyraprotocold2:
    image: local:e2etest-klyraprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /klyraprotocol/chain/.carl
       - --p2p.persistent_peers
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@klyraprotocold0:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@klyraprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@klyraprotocold3:26656"
       - --sDAI-daemon-mock-no-yields
       - "true"
       - --sDai-daemon-enabled
       - "true"
       - --price-daemon-enabled
       - "true"
       - --deleveraging-daemon-enabled
       - "true"
    environment:
      - DAEMON_HOME=/klyraprotocol/chain/.carl
      - ETH_RPC_ENDPOINT
    volumes:
      - ../protocol/localnet/klyraprotocol2:/klyraprotocol/chain/.carl/data

  klyraprotocold3:
    image: local:e2etest-klyraprotocol
    entrypoint:
       - cosmovisor
       - run
       - start
       - --log_level
       - error
       - --home
       - /klyraprotocol/chain/.dave
       - --p2p.persistent_peers 
       - "17e5e45691f0d01449c84fd4ae87279578cdd7ec@klyraprotocold0:26656,47539956aaa8e624e0f1d926040e54908ad0eb44@klyraprotocold2:26656,5882428984d83b03d0c907c1f0af343534987052@klyraprotocold3:26656"
       - --sDAI-daemon-mock-no-yields
       - "true"
       - --sDai-daemon-enabled
       - "true"
       - --price-daemon-enabled
       - "true"
       - --deleveraging-daemon-enabled
       - "true"
    environment:
      - DAEMON_HOME=/klyraprotocol/chain/.dave
      - ETH_RPC_ENDPOINT
    volumes:
      - ../protocol/localnet/klyraprotocol3:/klyraprotocol/chain/.dave/data
