// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: klyraprotocol/bridge/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the bridge module's genesis state.
type GenesisState struct {
	// The parameters of the module.
	EventParams   EventParams   `protobuf:"bytes,1,opt,name=event_params,json=eventParams,proto3" json:"event_params"`
	ProposeParams ProposeParams `protobuf:"bytes,2,opt,name=propose_params,json=proposeParams,proto3" json:"propose_params"`
	SafetyParams  SafetyParams  `protobuf:"bytes,3,opt,name=safety_params,json=safetyParams,proto3" json:"safety_params"`
	// Acknowledged event info that stores:
	// - the next event ID to be added to consensus.
	// - Ethereum block height of the most recently acknowledged bridge event.
	AcknowledgedEventInfo BridgeEventInfo `protobuf:"bytes,4,opt,name=acknowledged_event_info,json=acknowledgedEventInfo,proto3" json:"acknowledged_event_info"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_42040f3d29acba36, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetEventParams() EventParams {
	if m != nil {
		return m.EventParams
	}
	return EventParams{}
}

func (m *GenesisState) GetProposeParams() ProposeParams {
	if m != nil {
		return m.ProposeParams
	}
	return ProposeParams{}
}

func (m *GenesisState) GetSafetyParams() SafetyParams {
	if m != nil {
		return m.SafetyParams
	}
	return SafetyParams{}
}

func (m *GenesisState) GetAcknowledgedEventInfo() BridgeEventInfo {
	if m != nil {
		return m.AcknowledgedEventInfo
	}
	return BridgeEventInfo{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "klyraprotocol.bridge.GenesisState")
}

func init() {
	proto.RegisterFile("klyraprotocol/bridge/genesis.proto", fileDescriptor_42040f3d29acba36)
}

var fileDescriptor_42040f3d29acba36 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4e, 0x02, 0x31,
	0x10, 0x87, 0x77, 0x91, 0x78, 0x58, 0xc0, 0xc3, 0x06, 0x23, 0xe1, 0xb0, 0x0a, 0xc6, 0xc4, 0x83,
	0xec, 0x26, 0xfa, 0x06, 0x24, 0x62, 0x34, 0x31, 0xd9, 0xc8, 0xcd, 0x0b, 0x96, 0x32, 0x94, 0x06,
	0x68, 0x9b, 0xb6, 0xfe, 0xe1, 0x2d, 0x7c, 0x2c, 0x8e, 0x1c, 0x3d, 0x19, 0x02, 0x2f, 0x62, 0x68,
	0x59, 0xd9, 0x4d, 0x7a, 0x9a, 0xe6, 0x37, 0x5f, 0xbe, 0x4e, 0x3b, 0x41, 0x7b, 0x3a, 0x5b, 0x48,
	0x24, 0x24, 0xd7, 0x1c, 0xf3, 0x59, 0x32, 0x94, 0x74, 0x44, 0x20, 0x21, 0xc0, 0x40, 0x51, 0x15,
	0x9b, 0x3c, 0xac, 0x17, 0x98, 0xd8, 0x32, 0xcd, 0x3a, 0xe1, 0x84, 0x9b, 0x30, 0xd9, 0x9d, 0x2c,
	0xdb, 0xbc, 0x71, 0xfa, 0x6c, 0x19, 0xc0, 0x07, 0x30, 0x3d, 0xa0, 0x6c, 0x9c, 0xd1, 0x2d, 0x27,
	0x2d, 0x90, 0x44, 0xf3, 0xfd, 0xe5, 0xed, 0x75, 0x29, 0xa8, 0x3e, 0xd8, 0x71, 0xfa, 0x1a, 0x69,
	0x08, 0x9f, 0x82, 0xaa, 0xf5, 0x58, 0xac, 0xe1, 0x5f, 0xf8, 0xd7, 0x95, 0xdb, 0x56, 0xec, 0x1a,
	0x32, 0xbe, 0xdf, 0x91, 0xa9, 0x01, 0xbb, 0xe5, 0xe5, 0xef, 0xb9, 0xf7, 0x52, 0x81, 0x43, 0x14,
	0xa6, 0xc1, 0x89, 0x90, 0x5c, 0x70, 0x05, 0x99, 0xad, 0x64, 0x6c, 0x97, 0x6e, 0x5b, 0x6a, 0xd9,
	0x82, 0xaf, 0x26, 0xf2, 0x61, 0xf8, 0x1c, 0xd4, 0x14, 0x1a, 0x83, 0x5e, 0x64, 0xc2, 0x23, 0x23,
	0x6c, 0xbb, 0x85, 0x7d, 0x83, 0x16, 0x7c, 0x55, 0x95, 0xcb, 0x42, 0x1c, 0x9c, 0x21, 0x3c, 0x65,
	0xfc, 0x73, 0x06, 0x23, 0x02, 0xa3, 0xdc, 0x0f, 0x36, 0xca, 0x46, 0x7c, 0xe5, 0x16, 0x77, 0x4d,
	0x31, 0xaf, 0x7f, 0x64, 0x63, 0xbe, 0x77, 0x9f, 0xe6, 0x5d, 0x87, 0xe6, 0xdb, 0x72, 0x13, 0xf9,
	0xab, 0x4d, 0xe4, 0xaf, 0x37, 0x91, 0xff, 0xbd, 0x8d, 0xbc, 0xd5, 0x36, 0xf2, 0x7e, 0xb6, 0x91,
	0xf7, 0xda, 0x23, 0x54, 0x4f, 0xde, 0x87, 0x31, 0xe6, 0xf3, 0xa4, 0xaf, 0x25, 0xa0, 0x79, 0x8f,
	0x32, 0xc4, 0x30, 0x74, 0xd2, 0x6c, 0x67, 0xca, 0xc4, 0x1d, 0x3c, 0x41, 0x94, 0x25, 0xff, 0x9b,
	0xfc, 0xca, 0x76, 0xa9, 0x17, 0x02, 0xd4, 0xf0, 0xd8, 0x34, 0xee, 0xfe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0x7f, 0x7e, 0x3e, 0x6e, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AcknowledgedEventInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.SafetyParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ProposeParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.EventParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.EventParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ProposeParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.SafetyParams.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.AcknowledgedEventInfo.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EventParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposeParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProposeParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SafetyParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SafetyParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcknowledgedEventInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AcknowledgedEventInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
