// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: klyraprotocol/subaccounts/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgClaimYieldsForSubaccount is the Msg/ClaimYieldsForSubaccount request type.
type MsgClaimYieldsForSubaccount struct {
	Id *SubaccountId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgClaimYieldsForSubaccount) Reset()         { *m = MsgClaimYieldsForSubaccount{} }
func (m *MsgClaimYieldsForSubaccount) String() string { return proto.CompactTextString(m) }
func (*MsgClaimYieldsForSubaccount) ProtoMessage()    {}
func (*MsgClaimYieldsForSubaccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_757dffd3681ed3e5, []int{0}
}
func (m *MsgClaimYieldsForSubaccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimYieldsForSubaccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimYieldsForSubaccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimYieldsForSubaccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimYieldsForSubaccount.Merge(m, src)
}
func (m *MsgClaimYieldsForSubaccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimYieldsForSubaccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimYieldsForSubaccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimYieldsForSubaccount proto.InternalMessageInfo

func (m *MsgClaimYieldsForSubaccount) GetId() *SubaccountId {
	if m != nil {
		return m.Id
	}
	return nil
}

// MsgClaimYieldsForSubaccountResponse is the Msg/ClaimYieldsForSubaccount
// response type.
type MsgClaimYieldsForSubaccountResponse struct {
}

func (m *MsgClaimYieldsForSubaccountResponse) Reset()         { *m = MsgClaimYieldsForSubaccountResponse{} }
func (m *MsgClaimYieldsForSubaccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimYieldsForSubaccountResponse) ProtoMessage()    {}
func (*MsgClaimYieldsForSubaccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_757dffd3681ed3e5, []int{1}
}
func (m *MsgClaimYieldsForSubaccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimYieldsForSubaccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimYieldsForSubaccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimYieldsForSubaccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimYieldsForSubaccountResponse.Merge(m, src)
}
func (m *MsgClaimYieldsForSubaccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimYieldsForSubaccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimYieldsForSubaccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimYieldsForSubaccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgClaimYieldsForSubaccount)(nil), "klyraprotocol.subaccounts.MsgClaimYieldsForSubaccount")
	proto.RegisterType((*MsgClaimYieldsForSubaccountResponse)(nil), "klyraprotocol.subaccounts.MsgClaimYieldsForSubaccountResponse")
}

func init() {
	proto.RegisterFile("klyraprotocol/subaccounts/tx.proto", fileDescriptor_757dffd3681ed3e5)
}

var fileDescriptor_757dffd3681ed3e5 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xca, 0xce, 0xa9, 0x2c,
	0x4a, 0x2c, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x2e, 0x4d, 0x4a, 0x4c, 0x4e,
	0xce, 0x2f, 0xcd, 0x2b, 0x29, 0xd6, 0x2f, 0xa9, 0xd0, 0x03, 0x8b, 0x0b, 0x49, 0xa2, 0xa8, 0xd1,
	0x43, 0x52, 0x23, 0x25, 0x9e, 0x9c, 0x5f, 0x9c, 0x9b, 0x5f, 0xac, 0x9f, 0x5b, 0x9c, 0xae, 0x5f,
	0x66, 0x08, 0xa2, 0x20, 0x7a, 0xa4, 0xb4, 0x70, 0x9b, 0x8b, 0x60, 0x43, 0xd4, 0x2a, 0x85, 0x71,
	0x49, 0xfb, 0x16, 0xa7, 0x3b, 0xe7, 0x24, 0x66, 0xe6, 0x46, 0x66, 0xa6, 0xe6, 0xa4, 0x14, 0xbb,
	0xe5, 0x17, 0x05, 0xc3, 0x15, 0x09, 0x99, 0x73, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x1b, 0xa9, 0xeb, 0xe1, 0x74, 0x8b, 0x1e, 0x42, 0x8b, 0x67, 0x4a, 0x10, 0x53, 0x66, 0x8a,
	0x92, 0x2a, 0x97, 0x32, 0x1e, 0x73, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x8d, 0x16,
	0x32, 0x72, 0x31, 0xfb, 0x16, 0xa7, 0x0b, 0x4d, 0x62, 0xe4, 0x92, 0xc0, 0xe9, 0x08, 0x33, 0x3c,
	0x16, 0xe3, 0xb1, 0x44, 0xca, 0x8e, 0x3c, 0x7d, 0x30, 0xc7, 0x49, 0xb1, 0x36, 0x3c, 0xdf, 0xa0,
	0xc5, 0xe8, 0x94, 0x7a, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31,
	0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0xde, 0xe9,
	0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xc1, 0x25, 0x45, 0xa9, 0x89, 0xb9,
	0x6e, 0x99, 0x79, 0x89, 0x79, 0xc9, 0xa9, 0xba, 0x01, 0xf0, 0xc0, 0x07, 0x0b, 0xeb, 0x26, 0x67,
	0x24, 0x66, 0xe6, 0xe9, 0xc3, 0xa3, 0xa4, 0x02, 0x35, 0xb2, 0x2b, 0x0b, 0x52, 0x8b, 0x93, 0xd8,
	0xc0, 0xb2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x5b, 0xae, 0x2d, 0x16, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ClaimYieldsForSubaccount claims the yields for the provided subaccount and
	// persists it to state.
	ClaimYieldsForSubaccount(ctx context.Context, in *MsgClaimYieldsForSubaccount, opts ...grpc.CallOption) (*MsgClaimYieldsForSubaccountResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimYieldsForSubaccount(ctx context.Context, in *MsgClaimYieldsForSubaccount, opts ...grpc.CallOption) (*MsgClaimYieldsForSubaccountResponse, error) {
	out := new(MsgClaimYieldsForSubaccountResponse)
	err := c.cc.Invoke(ctx, "/klyraprotocol.subaccounts.Msg/ClaimYieldsForSubaccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ClaimYieldsForSubaccount claims the yields for the provided subaccount and
	// persists it to state.
	ClaimYieldsForSubaccount(context.Context, *MsgClaimYieldsForSubaccount) (*MsgClaimYieldsForSubaccountResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimYieldsForSubaccount(ctx context.Context, req *MsgClaimYieldsForSubaccount) (*MsgClaimYieldsForSubaccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimYieldsForSubaccount not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimYieldsForSubaccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimYieldsForSubaccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimYieldsForSubaccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/klyraprotocol.subaccounts.Msg/ClaimYieldsForSubaccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimYieldsForSubaccount(ctx, req.(*MsgClaimYieldsForSubaccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "klyraprotocol.subaccounts.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimYieldsForSubaccount",
			Handler:    _Msg_ClaimYieldsForSubaccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "klyraprotocol/subaccounts/tx.proto",
}

func (m *MsgClaimYieldsForSubaccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimYieldsForSubaccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimYieldsForSubaccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != nil {
		{
			size, err := m.Id.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimYieldsForSubaccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimYieldsForSubaccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimYieldsForSubaccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClaimYieldsForSubaccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != nil {
		l = m.Id.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimYieldsForSubaccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClaimYieldsForSubaccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimYieldsForSubaccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimYieldsForSubaccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Id == nil {
				m.Id = &SubaccountId{}
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimYieldsForSubaccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimYieldsForSubaccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimYieldsForSubaccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
