syntax = "proto3";
package klyraprotocol.blocktime;

option go_package = "github.com/StreamFinance-Protocol/stream-chain/protocol/x/blocktime/types";

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "klyraprotocol/blocktime/blocktime.proto";

// Query defines the gRPC querier service.
service Query {
  // Queries the information of the previous block
  rpc PreviousBlockInfo(QueryPreviousBlockInfoRequest)
      returns (QueryPreviousBlockInfoResponse) {
        option (google.api.http) = {
          get: "/stream-chain/blocktime/previous_block_info"
        };
      }
}

// QueryPreviousBlockInfoRequest is a request type for the PreviousBlockInfo
// RPC method.
message QueryPreviousBlockInfoRequest {}

// QueryPreviousBlockInfoResponse is a request type for the PreviousBlockInfo
// RPC method.
message QueryPreviousBlockInfoResponse { BlockInfo info = 1; }
